(require "./ch08-3")

(use gauche.test)
(test-start "§ 8.3")
;(simplifier)
(define-macro (simp-test expr expected) (test* #`",expr" expected (simp expr)))
;(test-section "")
(simp-test '(3 * 2 * x)
           '(6 * x))
(simp-test '(2 * x * x * 3)
           '(6 * (x ^ 2)))
(simp-test '(2 * x * 3 * y * 4 * z * 5 * 6)
           '(720 * (x * (y * z))))
(simp-test '(3 + x + 4 + x)
           '((2 * x) + 7))
(simp-test '(2 * x * 3 * x * 4 * (1 / x) * 5 * 6)
           '(720 * x))

(test-section "")
(simp-test '(3 + x + 4 - x)
           '7)
(simp-test '(x + y + y + x)
           '(x + (y + (y + x))))
(simp-test '(3 * x + 4 * x)
           '((3 * x) + (4 * x)))

(test-end)