(require "./ch08-4")

(use gauche.test)
(test-start "§ 8.4")
;(simplifier)
(define-macro (simp-test expr expected) (test* #`",expr" expected (simp expr)))

;(simp-test '(d (f(x) / g(x)) / d x)
;          '(((g x) * (d (f x) / d x) - (f x) * (d (g x) / d x)) / (g x) ^ 2) )

(test-section "p.250")
(simp-test '(d (x + x) / d x)
           '2 )
(simp-test '(d (a * x ^ 2 + b * x + c) / d x)
           '((2 * (a * x)) + b) )
;(simp-test '(d ((a * x ^ 2 + b * x + c) / x) / d x)
;          '((((a * (x ^ 2)) + ((b * x) + c)) - (x * ((2 * (a * x)) + b)))
;            / (x ^ 2)) )
(simp-test '(d ((a * x ^ 2 + b * x + c) / x) / d x)
           '(((x * ((2 * (a * x)) + b)) - ((a * (x ^ 2)) + ((b * x) + c)))
             / (x ^ 2)) )

(simp-test '(log ((d (x + x) / d x) / 2))
           '0 )
(simp-test '(log(x + x) - log x)
           '(log 2) )
(simp-test '(x ^ cos pi)
           '(1 / x) )
;(simp-test '(d (3 * x + (cos x) / x) / d x)
;          '((((cos x) - (x * (- (sin x)))) / (x ^ 2)) + 3) )
(simp-test '(d (3 * x + (cos x) / x) / d x)
           '((((x * (- (sin x))) - (cos x)) / (x ^ 2)) + 3) )
;(simp-test '(d ((cos x) / x) / d x)
;          '(((cos x) - (x * (- (sin x)))) / (x ^ 2)) )
(simp-test '(d ((cos x) / x) / d x)
           '(((x * (- (sin x))) - (cos x)) / (x ^ 2)) )
(simp-test '(d (3 * x ^ 2 + 2 * x + 1) / d x)
           '((6 * x) + 2) )
(simp-test '(sin(x + x) ^ 2 + cos(d x ^ 2 / d x) ^ 2)
           '1)
(simp-test '(sin(x + x) * sin(d x ^ 2 / d x) +
                cos(2 * x) * cos(x * d 2 * y / d y))
           '1)
(test-end)